### PR TITLE
Add `summarize` as an explicit alias of the function `summarise`

### PR DESCRIPTION
**Pull request by william-hutchison**
This pull request adds `summarize` as an explicit alias of the function `summarise`. This change increases consistency between tidySingleCellExperiment and dplyr.

### CODE REVIEW

**Review by stemangiola — CHANGES_REQUESTED** [review]
- the version should be 1.10.0
- you should have a unit test almost every time you change or add something
- We have some conflicts apparently

**Comment by william-hutchison** [comment]
I have added a test for the summarize alias and manually resolved the conflict. It was caused by us both updating the version number. I have now set the version number to 1.12.0, upgrading from 1.11.1.

**Review by stemangiola — CHANGES_REQUESTED** [review]
Sorry, the version should be 1.11.2

also, ask to "review" only after at least one github action has passed green.

**Comment by stemangiola** [comment]
`Error: object ‘aggregate_cells’ is not exported by 'namespace:ttservice'`

@william-hutchison I think you have to force the service version like it is in `tidyseurat`

**Review by stemangiola — APPROVED** [review]
well done!

**Comment by william-hutchison** [comment]
Thanks for your help!

**Pull request merged**
