### PR TITLE
method documentation & vignette revision

### PR DESCRIPTION
**Pull request by HelenaLC**
- vignette revision according as discussed at #72, including
  - loading full set dependencies in the preamble
  - fixing vignette HTML rendering on Bioc (see [here](https://bioconductor.org/packages/release/bioc/vignettes/tidySingleCellExperiment/inst/doc/introduction.html))
  - hyperlinking external packages using `BiocStyle::CRAN/Biocpkg()` and friends
  - consistent style to improve readability and distinguish between, e.g.,  
ecosystems (*tidyverse*), classes/variables (`tibble`), functions (`unnest()`) 
  - prettify table summarizing `tidySingleCellExperiment`'s functionality
- method documentation revision as proposed at #72, including
  - inheriting man pages from parent `dplyr`, `tidyr`, ..., methods
  - minor fixed for consistent style and ordering of roxygen headers
  - added `attach.R` and `zzz.R` from #69 to assure needed dependencies are attached
- outstanding pain points:
  - rather than `attach.R` and `zzz.R`, would depending (instead of importing) packages be an option? how to other tidy packages deal with defining for S3 methods for foreign generics?
  - `dplyr`'s `bind_rows/cols()` masks the `ttservice` version; currently  
  need to write `ttservice::bind_rows/cols()` for methods to work 
- the good news:
  - R CMD check is currently clean
  - `devtools::document()` is warning-free

### CODE REVIEW

**Review by stemangiola — COMMENTED** [review]
Thanks @HelenaLC !

1) I notice that we have repetitions (that's an old problem, this is likely true for all methods) such as 

```r
?bind_rows

Description
This is an efficient implementation of the common pattern of 'do.call(rbind, dfs)' or 'do.call(cbind, dfs)' for binding many data frames into one.

This is an efficient implementation of the common pattern of 'do.call(rbind, dfs)' or 'do.call(cbind, dfs)' for binding many data frames into one.

Details
The output of 'bind_rows()' will contain a column if that column appears in any of the inputs.

The output of 'bind_rows()' will contain a column if that column appears in any of the inputs.

Value
'bind_rows()' and 'bind_cols()' return the same type as the first input, either a data frame, 'tbl_df', or 'grouped_df'.

'bind_rows()' and 'bind_cols()' return the same type as the first input, either a data frame, 'tbl_df', or 'grouped_df'.
```

2) For the bind_rows example, I would prefer to avoid `ttservice::`, or replace it with `tidySingleCellExperiment::`, as users should not know about ttservice. 

3) One thing I was trying to clean is to drop all

```r
`%>%` <- magrittr::`%>%`
```

From the documentation and use the base pipe `|>` everywhere

4) I noticed that if I do `?slice` the documentation includes all methods, e.g.


```r
`%>%` <- magrittr::`%>%`
pbmc_small %>%

    arrange(nFeature_RNA)

`%>%` <- magrittr::`%>%`
pbmc_small %>%

    distinct(groups)


`%>%` <- magrittr::`%>%`
pbmc_small %>%

    filter(groups == "g1")

# Learn more in ?dplyr_tidy_eval

`%>%` <- magrittr::`%>%`
pbmc_small %>%

    group_by(groups)

`%>%` <- magrittr::`%>%`
pbmc_small %>%

    summarise(mean(nCount_RNA))
    ```

this is also true for `?select` and I assume for other methods as well.

**Comment by stemangiola** [comment]
> outstanding pain points:
> * rather than `attach.R` and `zzz.R`, would depending (instead of importing) packages be an option? how to other tidy packages deal with defining for S3 methods for foreign generics?

I took those files from the tidyverse package.  Would add them to depend load those package analogously to attach.R does?

Maybe changing this could be another pull request. I am never against simplifying stuff ;)

> * `dplyr`'s `bind_rows/cols()` masks the `ttservice` version; currently
>   need to write `ttservice::bind_rows/cols()` for methods to work

Yes I'm not sure why `bind_*` have not been developed as methods. I would prefer using `tidySingleCellExperiment::` because `ttservice` should be completely hidden from the user.

If only `tidySingleCellExperiment` is loaded or loaded last, this is not a problem. However, I understand that this explicit declaration makes the example more robust.

**Comment by stemangiola** [comment]
> the good news:
> * R CMD check is currently clean
> * `devtools::document()` is warning-free

Amazing!

**Comment by HelenaLC** [comment]
For 1. I think this is could be due to how ttservice documents them, but will doublecheck. I.e., we get what we inherit, so fixing it upstream might resolve it. 

2.-4. Agreed & I can fix those. 
Re depending vs. attaching - I am not sure. I‘ll try to give it a shirt and see first hand. Plus do some research. Let‘s see!

Re bind_rows etc., still worth thinking about how we can resolve this. Eg, as a user, I get pretty confused with non-informative errors because some other method was dispatched :/

**Comment by stemangiola** [comment]
> For 1. I think this is could be due to how ttservice documents them, but will doublecheck. I.e., we get what we inherit, so fixing it upstream might resolve it.

Let's think about this after this PR then.


> 2.-4. Agreed & I can fix those.

When these are done, most likely the PR is good to go!

Looking forward to accept it. 

(also please have a look if they pass the github actions, before requiring code review)

**Comment by HelenaLC** [comment]
Hm. I wonder if these fails could be related to older R/Bioc versions in the GHA? I could not reproduce them on R 4.3/Bioc 3.17, so am a bit stuck how to fix this.

**Comment by stemangiola** [comment]
> Hm. I wonder if these fails could be related to older R/Bioc versions in the GHA? I could not reproduce them on R 4.3/Bioc 3.17, so am a bit stuck how to fix this.

I see just one warning

```
Warning: declared S3 method 'rename.SingleCellExperiment' not found
```

must be some little bug, I don't think it depends on versions of R/Bioc

**Comment by HelenaLC** [comment]
> > Hm. I wonder if these fails could be related to older R/Bioc versions in the GHA? I could not reproduce them on R 4.3/Bioc 3.17, so am a bit stuck how to fix this.
> 
> I see just one warning
> 
> ```
> Warning: declared S3 method 'rename.SingleCellExperiment' not found
> ```
> 
> must be some little bug, I don't think it depends on versions of R/Bioc

Yeah, I think you're right - maybe this'll fix it! Maybe worth considering to eventually up GHA versions in any case, just to be sure we're testing in the same realm as Bioc servers will (as to not get unexpected build/check warnings/errors when pushing upstream).

**Comment by stemangiola** [comment]
> > > Hm. I wonder if these fails could be related to older R/Bioc versions in the GHA? I could not reproduce them on R 4.3/Bioc 3.17, so am a bit stuck how to fix this.
> > 
> > 
> > I see just one warning
> > ```
> > Warning: declared S3 method 'rename.SingleCellExperiment' not found
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > must be some little bug, I don't think it depends on versions of R/Bioc
> 
> Yeah, I think you're right - hoping this'll fix it! Maybe worth considering to eventually up GHA versions in any case, just to be sure we're testing in the same realm as Bioc servers will (as to not get unexpected build/check warnings/errors when pushing upstream).

Let's see. It a bit annoying that I have to approve the unit tests every time. You could even PR onto your master and test, and push your master into mine.

But hopefully this will go fine.

**Comment by HelenaLC** [comment]
Replaced by #75

**Pull request closed without merging**
