### PR TITLE
Allow y as S4 DataFrame in *_join()

### PR DESCRIPTION
**Pull request by lambdamoses**
Address #80

### CODE REVIEW

**Comment by stemangiola** [comment]
Somehow your comment about refactoring disappeared, I must have clicked on something weird.

Regarding your refectory, I cannot figure out whether your factoring proposal would only decrease complexity or also increase complexity somehow. If it's not a lot of work for you to re-factor the code, can I please ask you to do so in a separate branch so we can evaluate whether to keep or reject the proposal?

On the other hand, if it's a lot of work, there might be other priorities beyond this.

**Comment by lambdamoses** [comment]
No, it isn't a lot for work. It will decrease the complexity, since it's really one function behind all 4 join flavors. I'll do it in a branch in my fork of your repo. However, it might make debugging a bit more complicated.

**Comment by lambdamoses** [comment]
> Somehow your comment about refactoring disappeared, I must have clicked on something weird.

The comment is in the issue, not this pull request.

**Comment by lambdamoses** [comment]
See the refactoring here: https://github.com/lambdamoses/tidySingleCellExperiment/blob/bcd3f5529948e9cff2f317bbf001558db9986bae/R/dplyr_methods.R#L329

**Pull request merged**
