### PR TITLE
prettifying vignette revision (formatting, hyperlinks etc.)

### PR DESCRIPTION
**Pull request by HelenaLC**
(Note: branched out from `solve-conflict-tidyverse` PR #69, hence these changes are included here as well. Alternatively, could do a separate PR once #69 has been resolved.)

Vignette revision as discussed at #72, including:
  - loading full set dependencies in the preamble
  - fixing vignette HTML rendering on Bioc (see [here](https://bioconductor.org/packages/release/bioc/vignettes/tidySingleCellExperiment/inst/doc/introduction.html))
  - hyperlinking external packages using `BiocStyle::CRAN/Biocpkg()` and friends
  - consistent style to improve readability and distinguish between, e.g.,  
ecosystems (*tidyverse*), classes/variables (`tibble`), functions (`unnest()`) 
  - prettify table summarizing `tidySingleCellExperiment`'s functionality
  
...perhaps best to look at the HTML version of this, and compare to the Bioc one for review!

### CODE REVIEW

**Comment by stemangiola** [comment]
Looks great. However, branching from https://github.com/stemangiola/tidySingleCellExperiment/pull/69 is not great because it fails the checks for a reason I could not solve so far (cannot find filter method due to some `roxygen` mystery).

Apologies, would you mind branching from master in this case and putting your new vignette there?

Thanks!

**Comment by HelenaLC** [comment]
Sure, no problem, will do! Re documentation: I have a running version that is warning-free (at least for me, I was getting devtools::document() warnings previously). That PR will look huge (1000s of character changes), as I am dropping all manual documentation (except for utility functions), and am inheriting most from dplyr/tidyr/… That been said, I propose a PR with 1 dplyr and 1 tidyr function; check that man page for whether it’s acceptable; then PR the rest. Or you have a suggestion?

I think it’ll be super nice in that long-term maintenance will be much easier, and it’s as comprehensive as we can be. Plus, bringing script lengths down by 100s of characters makes it a lot neater. And we can focus future efforts on useful (transcriptomics) examples.

**Comment by stemangiola** [comment]
> I am dropping all manual documentation (except for utility functions), and am inheriting most from dplyr/tidyr/

sounds good, the only specific thing are examples, which use SCE instead of a tibble, and little more. So more we manage to use from tidyverse and better it is.

> That been said, I propose a PR with 1 dplyr and 1 tidyr function; check those man pages for whether they’re acceptable; then PR the rest. Or you have a suggestion?

I did not understand this one.

**Comment by stemangiola** [comment]
maybe 

- one PR from master with vignette and 
- one PR from master for documentation

But if you have done all together it's also fine. Happy to review it when it's ready.

**Comment by HelenaLC** [comment]
All I meant was that I could do a small PR with 1 function documentation update, so it’s easy to check the “new style”, or do all at once (but that’s affect maaany files and might be difficult to review)- you’re call 🙏

**Pull request closed without merging**
