### PR TITLE
Test not prefacing functions with packages

### PR DESCRIPTION
**Pull request by mblue9**
It doesn't pass the checks but can you check if this is what I was meant to change to test?
i.e. replacing all :: with @importFrom 
not sure if I added the ones in the right places when there's multiple @export for a function

if this is what I was supposed to test and it's confirmed to not pass here we can close this.

### CODE REVIEW

**Comment by mblue9** [comment]
I only tested changing dplyr-methods.R to see if that would work first.

**Comment by stemangiola** [comment]
Hello @mblue9 thanks I converted the single-cell to bioconductor , tomorrow I will help! :)

**Comment by stemangiola** [comment]
Thanks Maria,

I think this problem is connected with the fact (Martins unresolved point) that we are re-defining the tidyverse generics + xxx.default, and so we need to specify :: within the `.default` methods. I tried to eliminate the generics and .default (looking at plyranges) however,

[...]
I worked on it, and I agree. Respecting this standard is on out to-do list for tidySCE, tidySE and tidybulk. However I was not able to make things work under this standard this branch (either the export from roxigen disappears, or the method.class does not get exported). I ask to give us a release cycle to fix this. This although is a better approach does not affect negatively when using any package.

**Comment by mblue9** [comment]
I think this is not needed now so closing.

**Comment by stemangiola** [comment]
> 
> 
> I think this is not needed now so closing.

I complied with Morgan request of dropping the generics for 
- tidySCE
- tidySE
- tidyseurat
- tidybulk

But I ended up not going deeper into this matter. I think is really marginal, but who knows, in the future we might try to polish this aspect..

**Pull request closed without merging**
